import assert from 'node:assert/strict';
import {test} from 'node:test';
import fs from 'node:fs';
import {
  rowDisposition, mergePackMetadata, decimalIdentity, validateAction,
  validateRecoveryReceipt, fingerprint, verifyExecutionCases
} from '../scripts/delight-price-release-core.mjs';
const ready={sheet_row:2,row_colour:'none',retail_proposed:'85.00',wholesale_proposed:'58.00'};
const org='acc82cb4-95ab-4081-8894-17ef22914a68';
const action={table:'retail_sellable_products',key:{id:'offer'},before:{id:'offer',organisation_id:org,product_id:'product',rrp_price_amount:'80.000000'},patch:{rrp_price_amount:'85.00'},sheetRow:2};
const proof={environment:'prd',database:'mattanutra-prd',cluster:'cluster',manifestSha256:'manifest',restoreVerified:true,allTablesAndSequencesEqual:true,ownershipAndGrantsEqual:true,retention:'indefinite-until-user-authorizes-deletion',retentionUntil:null,startedAt:'2026-09-26T10:00:01Z',completedAt:'2026-09-26T10:00:02Z'};
const target={environment:'prd',database:'mattanutra-prd',cluster:'cluster',manifestSha256:'manifest',writersStoppedAt:'2026-09-26T10:00:00Z'};
test('DPR-01 pharmacy ambiguities are held even when the green retail is numeric',()=>{for(const n of [4,9,13,25,32,39,47,68,116])assert.equal(rowDisposition({...ready,sheet_row:n}),'PHARMACY_CLARIFICATION');assert.equal(rowDisposition(ready),'READY');});
test('DPR-02 exact replacement variants remain product-review dependencies',()=>{for(const n of [54,79,93])assert.equal(rowDisposition({...ready,sheet_row:n}),'PRODUCT_REVIEW_REQUIRED');assert.equal(rowDisposition({...ready,sheet_row:33}),'READY');});
test('DPR-03 strong red overrides stale prices while inherited pink is not removal',()=>{assert.equal(rowDisposition({...ready,row_colour:'FFFFC7CE'}),'DISABLE');assert.equal(rowDisposition({...ready,row_colour:'FFFCE4EC'}),'READY');});
test('DPR-04 existing verified UAT administration is retained when pack agrees',()=>{const old={route:'oral',physicalUnit:'tablet',unitsPerServing:2,doseIncrement:1,packQuantity:60,provenance:{status:'verified',sourceUrl:'https://label.example',sourceText:'label'}};assert.deepEqual(mergePackMetadata(old,{packQuantity:60,physicalUnit:'tablet',sourceText:'supplier'}),old);assert.throws(()=>mergePackMetadata(old,{packQuantity:30,physicalUnit:'tablet'}),/conflict/i);});
test('DPR-05 supplier pack does not invent oral route, servings or verification',()=>{const r=mergePackMetadata(null,{packQuantity:60,physicalUnit:'unknown',sourceText:'sheet C2'});assert.equal(r.route,'unknown');assert.equal(r.unitsPerServing,null);assert.equal(r.doseIncrement,null);assert.equal(r.provenance.status,'unverified');assert.equal(r.packQuantity,60);});
test('DPR-06 decimal identity is exact and preserves distinctions lost by floating point',()=>{assert.equal(decimalIdentity('85.000000'),'85');assert.equal(decimalIdentity('0.00'),'0');assert.notEqual(decimalIdentity('9007199254740992.01'),decimalIdentity('9007199254740992.02'));assert.throws(()=>decimalIdentity('NaN'));});
test('DPR-07 action whitelist protects other sellers, stock, global prices and held rows',()=>{validateAction(action,{organisationId:org});for(const patch of [{stock_quantity:0},{retail_price_amount:85},{product_id:'other'}])assert.throws(()=>validateAction({...action,table:'retail_product_stock',patch},{organisationId:org}));assert.throws(()=>validateAction({...action,before:{...action.before,organisation_id:'other'}},{organisationId:org}));assert.throws(()=>validateAction({...action,sheetRow:9},{organisationId:org}));assert.throws(()=>validateAction({...action,table:'products',patch:{price_amount:85}},{organisationId:org}));});
test('DPR-08 backup must be restored, retained, correctly bound and after quiescence',()=>{validateRecoveryReceipt(proof,target);for(const change of [{retentionUntil:'2026-10-26'},{restoreVerified:false},{database:'mattanutra-uat'},{manifestSha256:'other'},{startedAt:'2026-09-26T09:59:59Z'},{allTablesAndSequencesEqual:false},{ownershipAndGrantsEqual:false}])assert.throws(()=>validateRecoveryReceipt({...proof,...change},target));});
test('DPR-09 fingerprints are independent of key order and change with reviewed values',()=>{assert.equal(fingerprint({b:2,a:1}),fingerprint({a:1,b:2}));assert.notEqual(fingerprint({a:'85'}),fingerprint({a:'86'}));});
test('DPR-10 execution reconciliation rejects missing, skipped and repeated cases',()=>{verifyExecutionCases(['a','b'],[{id:'a',status:'passed'},{id:'b',status:'passed'}]);for(const cases of [[{id:'a',status:'passed'}],[{id:'a',status:'passed'},{id:'b',status:'skipped'}],[{id:'a',status:'passed'},{id:'a',status:'passed'}]])assert.throws(()=>verifyExecutionCases(['a','b'],cases));});
test('DPR-11 worksheet authority stays frozen with all 117 rows and original prices',()=>{const raw=fs.readFileSync(new URL('./fixtures/delight-price-release-sheet.json',import.meta.url));const sheet=JSON.parse(raw);assert.equal(fingerprint(raw),'c362f7da9cd6dd682bed879e48ebdc6c24b35741b54e462328fa6a4a77456376');assert.equal(sheet.rows.length,117);assert.equal(sheet.sheet,'Definitive Price List (2)');assert.equal(sheet.rows.find(r=>r.sheet_row===68).retail_proposed,'853.00');});
