import assert from "node:assert/strict";
import { afterEach, test } from "node:test";
import { installRealCatalogue, uninstallRealCatalogue, runtime, rpc, profile } from "../ax-refinement/helpers.ts";
import { resetPlanCreateInflightForTests, runAdmittedPlanOperation } from "../../lib/agentic/plan/service.ts";
import { admitPlanOperation, claimPlanOperation, updateClaimedOperation, cancelPlanOperation } from "../../lib/agentic/plan/operations.ts";
import { businessError } from "../../lib/agentic/contract/errors.ts";
import { toolResult } from "../../lib/agentic/mcp/rpc.ts";
import { bytes } from "./fixtures.ts";

afterEach(() => { resetPlanCreateInflightForTests(); uninstallRealCatalogue(); });
test("PAY-POLL-01 unchanged reads are small, ownership fenced and failure/cancellation cannot hide behind the committed revision", async () => {
  await installRealCatalogue("dev");
  const app = runtime("payload-status"), key = "payload-status-create-01";
  const created = await rpc(app, "plan", { operation: "create", idempotencyKey: key, request: profile("A6") });
  const ownerScope = "dev:mattanutra:ax-refinement:payload-status";
  const operation = await app.store.getPlanOperationByKey(ownerScope, key); assert.ok(operation);
  await runAdmittedPlanOperation({ store: app.store, config: app.config, operationId: operation.id });
  const args = { operation: "get", planHandle: created.planHandle, responseView: "status" };
  const first = await rpc(app, "plan", args); assert.equal(first.ok, true); assert.equal(first.responseView, "status");
  const same = await rpc(app, "plan", { ...args, knownResultVersion: first.resultVersion });
  assert.equal(same.unchanged, true); assert.ok(!("options" in same));
  assert.ok(bytes(toolResult(same)) < 4096); assert.ok(bytes(toolResult(same)) < bytes(toolResult(created)) * .1);
  const stranger = runtime("other-owner", app.store);
  assert.equal((await rpc(stranger, "plan", { ...args, knownResultVersion: first.resultVersion })).ok, false);
  const admitted = await admitPlanOperation(app.store, { planId: operation.planId, ownerScope, key: "payload-pending-revision-02", payload: { operation: "revise", requestPatch: {} }, expectedRevision: 1, revision: 2, prepared: operation.command.prepared, scope: app.scope, now: app.now! });
  // Hold a lease: polling must observe this operation, never start another match.
  const claim = await claimPlanOperation(app.store, admitted.id, "held-worker", app.now!); assert.ok(claim);
  const pending = await rpc(app, "plan", { ...args, knownResultVersion: first.resultVersion });
  assert.equal(pending.unchanged, false); assert.equal(pending.revision, 1); assert.equal(pending.pendingRevision, 2);
  await updateClaimedOperation(app.store, claim, { status: "failed", error: businessError({ reasonCode: "temporarily_unavailable", message: "Dependency failed" }) }, app.now!);
  const failed = await rpc(app, "plan", { ...args, knownResultVersion: pending.resultVersion });
  assert.equal(failed.unchanged, false); assert.equal(failed.operationStatus, "failed"); assert.equal(failed.error.message, "Dependency failed"); assert.equal(failed.revision, 1);
  const replacement = await admitPlanOperation(app.store, { planId: operation.planId, ownerScope, key: "payload-pending-revision-03", payload: { operation: "revise", requestPatch: {} }, expectedRevision: 1, revision: 2, prepared: operation.command.prepared, scope: app.scope, now: app.now! });
  await cancelPlanOperation(app.store, replacement.id, app.now!);
  const cancelled = await rpc(app, "plan", { ...args, knownResultVersion: failed.resultVersion });
  assert.equal(cancelled.unchanged, false); assert.equal(cancelled.operationStatus, "cancelled");
  const before = await app.store.getPlanRevision(operation.planId, 1); assert.ok(before);
  await app.store.updatePlanRevision(operation.planId, 1, { result: { ...before.result, summary: "Updated visible advice" } });
  const changed = await rpc(app, "plan", { ...args, knownResultVersion: cancelled.resultVersion });
  assert.equal(changed.unchanged, false);
});
