import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, it } from "node:test";
import { captureAssessment } from "../../lib/assessment-capture.ts";
import { getSql, closeSqlPool } from "../../lib/db.ts";
import { loadGenerationInput } from "../../lib/assessment-revisions.ts";
import { createPharmacyOrder } from "../../lib/pharmacy-orders.ts";
import { getAdminFlowData } from "../../lib/admin-flow-data.ts";
import { emptyAdminDashboardFilters } from "../../lib/admin-dashboard-filters.ts";
import { createAssessmentResumeDraft, getAssessmentResumeDraft } from "../../lib/assessment-resume-store.ts";
import { seedPharmacyFixture } from "../helpers/pharmacy-fixture.ts";
import { fixtureDatabaseUrl } from "../helpers/fixture-teardown.ts";
fixtureDatabaseUrl(); const sql = getSql()!; after(closeSqlPool);
const answers = { firstName: "Source Fixture", sex: "male", age: "36-45", goals: ["energy"] };
function bpm(source: string, ray: string) { return { ray, attribution: { trafficSource: "pharmacy", sourceDetail: source } }; }
it("PHARM-SRC-PG-01 capture and resume preserve acquisition independently of generated input", async () => {
  const fixture = await seedPharmacyFixture("en", false), ray = randomUUID();
  const draft = await createAssessmentResumeDraft({ answers, locale: "en", contactEmail: "source@example.test", pharmacyId: fixture.slug, bpm: bpm("business_card", ray) } as Parameters<typeof createAssessmentResumeDraft>[0]);
  const storedDraft = await getAssessmentResumeDraft(draft.token);
  assert.ok(storedDraft);
  assert.deepEqual((storedDraft.answers as typeof answers & {inStorePharmacy: {acquisition: unknown}}).inStorePharmacy.acquisition, {source: "business_card", ray});
  const captured = await captureAssessment({ answers, locale: "en", pharmacyId: fixture.slug, resumeToken: draft.token, bpm: bpm("in_store", randomUUID()) }, {idempotencyKey: randomUUID()});
  const [stored] = await sql`select answers from public.assessments where plan_id=${captured.planId}::uuid`;
  assert.deepEqual(stored.answers.inStorePharmacy.acquisition, {source: "business_card", ray});
  const input = await loadGenerationInput(sql, captured.planId);
  assert.ok(input); assert.equal((input.answers.inStorePharmacy as Record<string, unknown>).acquisition, undefined);
});
it("PHARM-SRC-PG-02 unpaid order retains source and funnel deduplicates retries without paid conversions", async () => {
  const fixture = await seedPharmacyFixture(), ray = randomUUID();
  // Tracking metadata is independent of the already-completed fixture result.
  await sql`update public.assessments set answers=jsonb_set(answers,'{inStorePharmacy,acquisition}',${sql.json({source:"business_card",ray})}) where plan_id=${fixture.planId}::uuid`;
  const input = {planId: fixture.planId, pharmacy: fixture.slug, locale: "en", expectedRevision: fixture.revision, productIds: fixture.productIds, customerName: "Source Fixture"};
  const key = randomUUID(); const receipt = await createPharmacyOrder(input,key);
  assert.deepEqual(await createPharmacyOrder(input,key), receipt);
  const [order] = await sql`select metadata from public.retail_customer_orders where id=${receipt.id}::uuid`;
  assert.deepEqual(order.metadata.acquisition, {source:"business_card",ray});
  const flow = await getAdminFlowData("all", {...emptyAdminDashboardFilters, planId: fixture.planId});
  const rows = (flow as typeof flow & {pharmacySources?: Array<{source:string; orders:number}>}).pharmacySources;
  assert.ok(rows, "Pharmacy sources must be visible in the funnel");
  assert.equal(rows.find(row=>row.source==="business_card")?.orders,1);
  assert.equal(flow.nodes.find(row=>row.id==="precisionPaid")?.count,0);
  const {getAdminCustomerInsightsData}=await import("../../lib/admin-customer-insights.ts");
  const insights=await getAdminCustomerInsightsData("day",{enrichSegments:false});
  assert.equal(insights.databaseAvailable,true);
  const customer=insights.customers.find(row=>row.planId===fixture.planId);
  assert.ok(customer); assert.match(customer.source!,/Business-card QR/);
  assert.equal(customer.funnelStage,"order_placed_unpaid");
  assert.equal(customer.orderNumber,receipt.reference);
  assert.equal(customer.selectedPlan,null);
});
it("PHARM-SRC-PG-03 same-key capture without browser metadata stays idempotent and historical source stays unknown", async () => {
  const fixture=await seedPharmacyFixture("en",false), key=randomUUID();
  const body={answers,locale:"en",pharmacyId:fixture.slug};
  const first=await captureAssessment(body,{idempotencyKey:key});
  assert.deepEqual(await captureAssessment(body,{idempotencyKey:key}),first);
  const [before]=await sql`select input_hash, input_revision, answers from public.assessments where plan_id=${first.planId}::uuid`;
  assert.equal(before.answers.inStorePharmacy.acquisition.source,"unknown");
  const revised=await captureAssessment({...body, expectedRevision:first.revision,bpm:bpm("business_card",randomUUID())},{planId:first.planId,idempotencyKey:randomUUID()});
  assert.equal(revised.revision,first.revision);
  const [after]=await sql`select input_hash, input_revision, answers from public.assessments where plan_id=${first.planId}::uuid`;
  assert.deepEqual(after,before);
  const sessionId=randomUUID();
  const entry={...body,sessionId,bpm:bpm("business_card",sessionId)};
  const original=await captureAssessment(entry,{idempotencyKey:randomUUID()});
  const replay=await captureAssessment({...entry,bpm:bpm("in_store",randomUUID())},{idempotencyKey:randomUUID()});
  assert.equal(replay.planId,original.planId);
  const [saved]=await sql`select answers from public.assessments where plan_id=${original.planId}::uuid`;
  assert.deepEqual(saved.answers.inStorePharmacy.acquisition,{source:"business_card",ray:sessionId});
});
it("PHARM-SRC-PG-04 funnel uses durable source, locale and period while repeated paid-like browser events cannot count orders", async () => {
  const {writeBpmEvent}=await import("../../lib/bpm.ts");
  const fixture=await seedPharmacyFixture("th",false), ray=randomUUID();
  await sql`update public.assessments set answers=jsonb_set(answers,'{inStorePharmacy,acquisition}',${sql.json({source:"business_card",ray})}) where plan_id=${fixture.planId}::uuid`;
  for(const eventName of ["assessment_started","assessment_started","formulation_page_viewed","retail_order_created"]) await writeBpmEvent({eventName,eventType:"funnel",eventStatus:"paid",planId:fixture.planId,ray,locale:"th",attribution:{trafficSource:"pharmacy",sourceChannel:fixture.slug,sourceDetail:"in_store"}});
  const filters={...emptyAdminDashboardFilters,planId:fixture.planId,locale:"th"};
  const flow=await getAdminFlowData("day",filters);
  assert.equal(flow.databaseAvailable,true);
  const row=flow.pharmacySources?.find(row=>row.source==="business_card");
  assert.ok(row);assert.equal(row.started,1);assert.equal(row.revealed,1);assert.equal(row.orders,0);
  assert.equal(flow.summary.converted,0);
  assert.deepEqual((await getAdminFlowData("day",{...filters,locale:"en"})).pharmacySources,[]);
  await sql`update public.bpm set occurred_at=now()-interval '2 days' where plan_id=${fixture.planId}::uuid`;
  assert.deepEqual((await getAdminFlowData("day",filters)).pharmacySources,[]);
});
