import type { Locale } from "@/lib/i18n";
const en = {
  title: "Building your personalised supplement plan",
  complete: "ANALYSIS COMPLETE",
  payoff: "You have stopped guessing. Now you know.",
  inputs: [
    "Your answers",
    "Scientific evidence",
    "MattaNutra algorithms",
    "Thai FDA–registered products",
    "AI-assisted analysis",
  ],
  combining: "Combining five sources of insight",
  caption: "Working together to find what fits you",
  rain: "Considering nutrients and supplement compounds",
  clarity: "Bringing your personalised plan into focus",
  possibilities: "Nutrients and supplement compounds",
  selected: "ingredients selected for",
  you: "YOU",
  waiting: "Still preparing your personalised plan",
  matching: "Matching your",
  personalised: "PERSONALISED",
  matchingEnd: "plan to supplements at this pharmacy",
  estimate: "This usually takes about a minute.",
  ready: "Your personalised supplement plan is ready",
  matched: "Matched",
  at: "At",
  orderTitle: "Confirm your pharmacy order",
  help: "Untick any product you do not want or already have. Your item count and total update immediately.",
  items: "products selected",
  preConfirm: "Your order is ready to send to the pharmacist.",
  later: "When you have more time",
  coffeeTitle:
    "Discover the science and surprisingly detailed thinking behind your personalised plan.",
  coffeeBody:
    "There is much more here than a list of products. Explore what MattaNutra considered, what was selected, why it was selected and how all the pieces fit together.",
  quote: "“There’s some seriously clever thinking behind your plan.”",
  line: "Save my complete plan to LINE",
  or: "or",
  read: "Read My Detailed Plan Now",
  noLine: "Don’t use LINE?",
  save: "Save this private link and open it in any browser.",
  copy: "Copy link",
  copied: "Private plan link copied.",
  print: "Keep your private plan link so you can return to your plan anytime.",
  failed:
    "This is taking longer than expected. Your saved answers are safe. Try again to continue.",
  saving: "Saving your answers…",
};
type Copy = {
  [K in keyof typeof en]: (typeof en)[K] extends string[] ? string[] : string;
};
const th: Copy = {
  title: "กำลังจัดแผนอาหารเสริมเฉพาะคุณ",
  complete: "วิเคราะห์เสร็จแล้ว",
  payoff: "เลิกเดา เริ่มรู้จริง",
  inputs: [
    "คำตอบของคุณ",
    "หลักฐานทางวิทยาศาสตร์",
    "อัลกอริทึม MattaNutra",
    "ผลิตภัณฑ์ที่ขึ้นทะเบียน อย.",
    "การวิเคราะห์ด้วย AI",
  ],
  combining: "ผสานข้อมูลจากห้าแหล่ง",
  caption: "ทำงานร่วมกันเพื่อค้นหาสิ่งที่เหมาะกับคุณ",
  rain: "พิจารณาสารอาหารและส่วนประกอบอาหารเสริม",
  clarity: "กำลังจัดแผนเฉพาะคุณให้ชัดเจน",
  possibilities: "สารอาหารและส่วนประกอบอาหารเสริม",
  selected: "สารอาหารที่คัดเลือกสำหรับ",
  you: "คุณ",
  waiting: "กำลังเตรียมแผนเฉพาะบุคคลของคุณ",
  matching: "กำลังจับคู่แผน",
  personalised: "เฉพาะคุณ",
  matchingEnd: "กับอาหารเสริมของร้านยานี้",
  estimate: "โดยปกติใช้เวลาประมาณ 1 นาที",
  ready: "แผนอาหารเสริมเฉพาะคุณพร้อมแล้ว",
  matched: "จับคู่แล้ว",
  at: "ที่",
  orderTitle: "ยืนยันรายการสั่งซื้อที่ร้านยา",
  help: "นำเครื่องหมายออกจากผลิตภัณฑ์ที่ไม่ต้องการหรือมีอยู่แล้ว จำนวนรายการและยอดรวมจะปรับทันที",
  items: "ผลิตภัณฑ์ที่เลือก",
  preConfirm: "รายการของคุณพร้อมส่งให้เภสัชกรแล้ว",
  later: "เมื่อคุณมีเวลามากขึ้น",
  coffeeTitle: "ค้นพบหลักการทางวิทยาศาสตร์และรายละเอียดเบื้องหลังแผนเฉพาะคุณ",
  coffeeBody:
    "มากกว่ารายการผลิตภัณฑ์ มาดูว่า MattaNutra พิจารณาอะไร เลือกอะไร เพราะเหตุใด และแต่ละส่วนทำงานร่วมกันอย่างไร",
  quote: "“มีแนวคิดที่รอบคอบอยู่เบื้องหลังแผนของคุณนะ”",
  line: "เก็บแผนฉบับเต็มไว้ใน LINE",
  or: "หรือ",
  read: "อ่านแผนฉบับละเอียดตอนนี้",
  noLine: "ไม่ได้ใช้ LINE?",
  save: "เก็บลิงก์ส่วนตัวนี้ไว้ แล้วเปิดผ่านเบราว์เซอร์ได้ทุกเมื่อ",
  copy: "คัดลอกลิงก์",
  copied: "คัดลอกลิงก์ส่วนตัวแล้ว",
  print: "เก็บลิงก์ส่วนตัวนี้ไว้เพื่อกลับมาอ่านแผนได้ทุกเมื่อ",
  failed:
    "ขั้นตอนนี้ใช้เวลานานกว่าปกติ คำตอบที่บันทึกไว้ยังอยู่ โปรดลองอีกครั้งเพื่อดำเนินการต่อ",
  saving: "กำลังบันทึกคำตอบ…",
};
const zh: Copy = {
  title: "正在制定您的个性化营养补充方案",
  complete: "分析完成",
  payoff: "不再猜测，开始了解。",
  inputs: [
    "您的回答",
    "科学证据",
    "MattaNutra 算法",
    "泰国 FDA 注册产品",
    "AI 辅助分析",
  ],
  combining: "正在整合五方面的信息",
  caption: "共同寻找适合您的方案",
  rain: "正在考虑营养素与营养补充成分",
  clarity: "正在梳理您的个性化方案",
  possibilities: "营养素与营养补充成分",
  selected: "种成分为您精选",
  you: "您",
  waiting: "仍在为您准备个性化方案",
  matching: "正在将您的",
  personalised: "个性化",
  matchingEnd: "方案与这家药房的营养补充产品匹配",
  estimate: "通常大约需要一分钟。",
  ready: "您的个性化营养补充方案已准备好",
  matched: "已匹配",
  at: "药房：",
  orderTitle: "确认您的药房订单",
  help: "取消勾选您不需要或已有的产品。所选产品数量与总价将立即更新。",
  items: "种已选产品",
  preConfirm: "您的订单已准备好提交给药剂师。",
  later: "当您有更多时间时",
  coffeeTitle: "了解个性化方案背后的科学依据与细致思考。",
  coffeeBody:
    "这不仅仅是一张产品清单。了解 MattaNutra 考虑了什么、选择了什么、为什么选择，以及各部分如何相互配合。",
  quote: "“您的方案背后有许多细致的思考。”",
  line: "将完整方案保存到 LINE",
  or: "或",
  read: "现在阅读我的详细方案",
  noLine: "不用 LINE？",
  save: "保存这个私人链接，随时用浏览器打开。",
  copy: "复制链接",
  copied: "私人方案链接已复制。",
  print: "保存您的私人方案链接，即可随时返回查看方案。",
  failed: "此步骤比预期更久。已保存的回答仍然保留，请重试以继续。",
  saving: "正在保存您的回答…",
};
export const combinedCopy: Record<Locale, Copy> = { en, th, "zh-CN": zh };
