/**
 * Agent Commercial Models
 *
 * This module defines the commercial relationship between MattaNutra (the platform)
 * and Fulfillment Agents (pharmacies / retail partners).
 *
 * IMPORTANT CLARIFICATION (June 2026):
 * MattaNutra is NOT the retailer. The Fulfillment Agent is the separate legal entity
 * that sells products to the customer. MattaNutra earns a platform / access fee.
 */

export type AgentCommercialModel = 
  | 'agent_direct_platform_fee';    // Only supported model: Customer pays Agent (the retailer) → Agent pays MattaNutra a platform fee %

// Note: The previous model where MattaNutra acted as the retailer ('platform_collected') 
// is explicitly out of scope and must not be implemented.

export type PlatformFeeType =
  | 'percentage_of_gross'           // Most common: e.g. 15% of revenue from platform customers
  | 'percentage_of_margin'
  | 'fixed_per_order'
  | 'fixed_monthly'
  | 'tiered_percentage';

export type AgentRateSchedule = {
  id: string;
  fulfillmentAgentId: string;
  commercialModel: AgentCommercialModel;
  feeType: PlatformFeeType;
  feeValue: number;                 // e.g. 0.15 for 15%, or 5000 for fixed amounts (in smallest currency unit)
  currency?: string;
  effectiveFrom: string;
  effectiveTo?: string | null;
  minimumFee?: number | null;
  maximumFee?: number | null;
  notes?: string;
};

/**
 * Represents revenue generated by a Fulfillment Agent that is attributable to MattaNutra.
 * This is the base on which platform fees are calculated in the primary model.
 */
export type AgentAttributedRevenue = {
  fulfillmentAgentId: string;
  periodStart: string;
  periodEnd: string;
  currency: string;
  grossRevenue: number;             // Total value of orders attributed to this agent in the period (customer paid the Agent)
  orderCount: number;
  platformFeeRate: number;          // The rate that was active during (most of) the period
  calculatedPlatformFee: number;    // grossRevenue * platformFeeRate (subject to min/max)
};

/**
 * The settlement obligation between the Agent and MattaNutra.
 */
export type AgentPlatformFeeSettlement = {
  id: string;
  fulfillmentAgentId: string;
  periodStart: string;
  periodEnd: string;
  attributedRevenue: AgentAttributedRevenue;
  platformFeeDue: number;
  currency: string;
  status: 'pending' | 'invoiced' | 'partially_paid' | 'paid' | 'disputed';
  dueDate: string;
  paidAt?: string | null;
  notes?: string;
};
