import type { Locale } from "@/lib/i18n";
import type { ConnectProvider } from "@/lib/connect";

type GuideCopy = { intro: string; requirements: string; steps: string[]; admin: string };
type ConnectCopy = {
  eyebrow: string; title: string; description: string; choose: string; nav: string; guide: string; back: string;
  benefitsTitle: string; benefits: [string, string][]; overview: [string, string][];
  requirements: string; steps: string; admin: string; connectionUrl: string; copyUrl: string; open: string;
  testTitle: string; testDescription: string; testPrompt: string; copyPrompt: string; starterTitle: string; starterPrompt: string; copyStarter: string;
  copied: string; copyFailed: string; manualCopy: string; preparing: string; waiting: string; verified: string; expired: string;
  unavailable: string; paused: string; retry: string; newLink: string; privacy: string; faqTitle: string; faqs: [string, string][];
  examplesTitle: string; examples: string[]; troubleshooting: string; troubleshootItems: [string, string][];
  reviewed: string; verifiedOn: string; pendingReview: string; officialHelp: string; guideTitle: string;
  summaryTitle: string; summaryNote: string; summaryColumns: string[]; summaryUnavailable: string;
  guides: Record<ConnectProvider, GuideCopy>;
};

export const connectCopy: Record<Locale, ConnectCopy> = {
  en: {
    eyebrow: "MATTANUTRA · CONNECT",
    title: "Your personal supplement plan, in the AI you already use.",
    description: "Bring MattaNutra into your AI conversation. Explore a supplement plan that fits you, then turn it into available products in Thailand.",
    choose: "Choose your AI", nav: "Connect your AI", guide: "Connection guide", back: "All connection guides",
    benefitsTitle: "From a conversation to a practical plan",
    benefits: [["Make it personal", "Talk through your goals, preferences and budget with the AI you already use."], ["Make it practical", "MattaNutra helps match your plan to real products available in Thailand."], ["Stay in control", "Review the options and costs before choosing whether to buy anything."]],
    overview: [["Choose your AI", "Check the account requirements and open its connection settings."], ["Add MattaNutra", "Copy your connection URL and add it as a custom remote connector."], ["Try it out", "Ask your AI to call MattaNutra. Return here to see server confirmation."]],
    requirements: "Before you start", steps: "Connect, step by step", admin: "Using a work or team account?",
    connectionUrl: "Connection URL", copyUrl: "Copy connection URL", open: "Open provider settings",
    testTitle: "Check your connection", testDescription: "After adding and enabling MattaNutra, paste this into a new conversation. Keep this page open and come back after the AI responds.",
    testPrompt: "Call MattaNutra’s info tool now with locale en and view overview. Use the actual tool response to explain what MattaNutra can do and which countries it supports. If the tool is unavailable, tell me rather than guessing.",
    copyPrompt: "Copy test prompt", starterTitle: "Your connection works. Make it yours.",
    starterPrompt: "Help me create a personal supplement plan with MattaNutra for products available in Thailand. First ask about my goals, budget, dietary preferences, medicines and current supplements. Explain the options and limitations, and let me review the plan before any purchase.",
    copyStarter: "Copy starter prompt", copied: "Copied", copyFailed: "Your browser could not copy this. Select the text below and copy it manually.", manualCopy: "Select text to copy", preparing: "Preparing your connection link…",
    waiting: "Waiting for a successful MattaNutra info call…", verified: "Connection verified by MattaNutra", expired: "This confirmation link has expired. Your MCP connection still works. For a new confirmation, copy a new link and replace the URL in your AI’s settings.",
    unavailable: "Confirmation is unavailable right now. You can still connect using the ordinary server URL below.", paused: "Automatic checking has paused. Run the test in your AI, then check again.", retry: "Check again", newLink: "Create a new confirmation link",
    privacy: "No MattaNutra account or API key is needed. Your confirmation link lasts 24 hours; keep it private. Verification confirms a tool call, not a completed plan or purchase.",
    faqTitle: "A few things to know",
    faqs: [["Where is MattaNutra available?", "Product matching and purchases currently support Thailand, in Thai baht (THB). You can use English, Thai or Simplified Chinese. Connecting from elsewhere does not extend product availability to another country."], ["What does connecting cost?", "MattaNutra does not charge a connection fee. Your AI provider may require a paid subscription or an administrator’s permission. Products and any paid MattaNutra services are separate purchases, shown before checkout."], ["Is this medical advice?", "MattaNutra supports general wellness planning. It does not diagnose or treat medical conditions. Discuss medicines, pregnancy and medical conditions with a qualified healthcare professional."], ["Does connecting buy anything?", "No. Connecting and running the test do not create a purchase. You choose whether to continue to a plan or checkout."], ["What is measured?", "We measure visits, setup actions and successful test calls to improve this connection journey. Campaign events contain the AI provider, language, stage and campaign identifiers, not your prompts, health information or supplement details. Saved advertising preferences still apply."]],
    examplesTitle: "Start with a question that matters to you",
    examples: ["Help me build a supplement plan around my goals and budget.", "Find available products in Thailand for my proposed plan.", "Explain the choices before I decide what to buy."],
    troubleshooting: "If something does not work",
    troubleshootItems: [["I cannot find custom connectors", "Use the provider’s website and check your subscription and workspace permissions. Some organization accounts require an administrator to add the connector first."], ["The AI answers without using MattaNutra", "Enable or select MattaNutra in the conversation, then run the test prompt again. A written answer alone is not a verified connection."], ["The AI responds but this page is still waiting", "Check that the full connection URL, including its connect_token, was saved. Return to the same browser used to create it. A plain /api/mcp URL works but cannot confirm this attempt."], ["My link expired or I changed browsers", "Create a new confirmation link here, replace the connector URL, and run the test again. An expired token never blocks ordinary MCP access."]],
    reviewed: "Official instructions reviewed", verifiedOn: "Connection last verified", pendingReview: "Account testing and setup screenshots are awaiting verification. These instructions follow the provider’s official guide.", officialHelp: "Official setup help", guideTitle: "Connect MattaNutra to",
    summaryTitle: "AI connection funnel", summaryNote: "All campaigns in this date range, by provider and language. Visits and actions count distinct browser sessions; verified counts successful setup attempts. Meta accepted means delivery acknowledged, not ad attribution.",
    summaryColumns: ["Provider", "Language", "Visits", "Selected", "URL copied", "Opened", "Prompt copied", "Verified calls", "Meta accepted"], summaryUnavailable: "Connection reporting is unavailable.",
    guides: {
      claude: { intro: "Add MattaNutra as a custom remote connector, then enable it in your conversation.", requirements: "Use Claude on the web for setup. Custom connectors are available on Free, Pro, Max, Team and Enterprise; Free accounts have a limit of one custom connector. Workspace policies may apply.", steps: ["Open Claude. Go to Customize → Connectors → + Add → Add custom connector.", "Name it MattaNutra. Paste the full connection URL from this page, then choose Continue.", "Review the detected settings and continue. Choose No sign in, then Add. MattaNutra does not need an API key or account login.", "Start a conversation. Use + → Connectors to enable MattaNutra, then paste the test prompt below."], admin: "Team owners, and Enterprise owners or roles permitted to manage Libraries, can add it through Organization settings → Connectors → Add → Custom → Web. Enter the URL, choose No sign in, and finish adding it. Members then connect from Customize → Connectors and enable it in their conversation. To change a saved URL, remove and re-add the connector." },
      perplexity: { intro: "Create a remote connector with no authentication and Streamable HTTP.", requirements: "Use the Perplexity website with an eligible Pro, Max or Enterprise account. Custom connector access can depend on organization settings and your subscription.", steps: ["Open Account settings → Connectors → + Custom connector.", "Choose Remote. Name the connector MattaNutra and paste the full connection URL from this page.", "Set authentication to None and transport to Streamable HTTP. Read and accept Perplexity’s connector acknowledgement, then choose Add.", "Enable or select MattaNutra for your conversation and paste the test prompt below."], admin: "Enterprise administrators control which custom connectors are available and shared in the organization. Ask your administrator to provision MattaNutra if you cannot add a connector yourself." },
      chatgpt: { intro: "Create and install a personal plugin, then use MattaNutra in a Work conversation.", requirements: "Use ChatGPT on the web with an account that supports Developer Mode and personal plugins. Workspace policy can restrict access. MattaNutra is not yet listed in the public plugin directory.", steps: ["Open Settings → Security and login and enable Developer mode.", "Go to Plugins and choose the plus button to create a personal plugin. Enter the full MattaNutra connection URL from this page. Select no authentication if asked.", "Finish creating the plugin, then find it under your personal plugins and use the plus button to install it.", "Open the Work tab and start a new Work chat. Type @ to select your MattaNutra plugin, then paste the test prompt below."], admin: "Your workspace administrator may need to allow Developer Mode and personal plugins. If these options are missing, check the official help and your account’s available features. A public directory search will not find this personal plugin." },
      grok: { intro: "Add a custom connector and use MattaNutra from your Grok conversation.", requirements: "Grok supports custom connectors. Use grok.com for setup; organization accounts may require an administrator to provision the connector first.", steps: ["Open Grok → Connectors → New Connector → Custom.", "Name the connector MattaNutra and enter the full connection URL from this page.", "Choose no authentication if asked, then save the connector. MattaNutra needs no API key or login.", "Select or enable MattaNutra in your conversation and paste the test prompt below."], admin: "For Business or Enterprise, an administrator can use console.x.ai → Grok Business → Connectors → + Add Connector → Other. Add the server URL and grant access to the appropriate members." }
    }
  },
  th: {
    eyebrow: "MATTANUTRA · เชื่อมต่อ", title: "แผนอาหารเสริมเฉพาะคุณ ใน AI ที่คุณใช้อยู่แล้ว",
    description: "ให้ MattaNutra ช่วยในบทสนทนา AI ของคุณ สำรวจแผนอาหารเสริมที่เหมาะกับคุณ แล้วค้นหาผลิตภัณฑ์ที่มีจำหน่ายในประเทศไทย",
    choose: "เลือก AI ของคุณ", nav: "เชื่อมต่อ AI", guide: "คู่มือการเชื่อมต่อ", back: "คู่มือการเชื่อมต่อทั้งหมด",
    benefitsTitle: "จากบทสนทนาสู่แผนที่นำไปใช้ได้จริง",
    benefits: [["เหมาะกับคุณ", "พูดคุยเรื่องเป้าหมาย ความต้องการ และงบประมาณกับ AI ที่คุณใช้เป็นประจำ"], ["เลือกสินค้าได้จริง", "MattaNutra ช่วยจับคู่แผนกับผลิตภัณฑ์ที่มีจำหน่ายในประเทศไทย"], ["คุณเป็นผู้ตัดสินใจ", "ตรวจสอบตัวเลือกและราคาก่อนตัดสินใจว่าจะซื้อหรือไม่"]],
    overview: [["เลือก AI", "ตรวจสอบข้อกำหนดบัญชีและเปิดการตั้งค่าการเชื่อมต่อ"], ["เพิ่ม MattaNutra", "คัดลอก URL แล้วเพิ่มเป็นตัวเชื่อมต่อระยะไกลแบบกำหนดเอง"], ["ลองใช้งาน", "ขอให้ AI เรียกใช้ MattaNutra แล้วกลับมาดูผลยืนยันจากเซิร์ฟเวอร์"]],
    requirements: "ก่อนเริ่มต้น", steps: "ขั้นตอนการเชื่อมต่อ", admin: "ใช้บัญชีองค์กรหรือทีมอยู่หรือไม่?", connectionUrl: "URL สำหรับเชื่อมต่อ", copyUrl: "คัดลอก URL เชื่อมต่อ", open: "เปิดการตั้งค่าผู้ให้บริการ",
    testTitle: "ตรวจสอบการเชื่อมต่อ", testDescription: "หลังจากเพิ่มและเปิดใช้ MattaNutra ให้วางข้อความนี้ในบทสนทนาใหม่ เปิดหน้านี้ไว้และกลับมาหลังจาก AI ตอบ",
    testPrompt: "เรียกใช้เครื่องมือ info ของ MattaNutra ตอนนี้ โดยกำหนด locale เป็น th และ view เป็น overview ใช้ผลลัพธ์จริงจากเครื่องมือเพื่ออธิบายเป็นภาษาไทยว่า MattaNutra ทำอะไรได้บ้างและรองรับประเทศใด หากเรียกใช้เครื่องมือไม่ได้ ให้บอกตามจริง อย่าคาดเดา",
    copyPrompt: "คัดลอกข้อความทดสอบ", starterTitle: "เชื่อมต่อสำเร็จ เริ่มสร้างแผนของคุณได้เลย",
    starterPrompt: "ช่วยสร้างแผนอาหารเสริมเฉพาะฉันด้วย MattaNutra โดยใช้ผลิตภัณฑ์ที่มีจำหน่ายในประเทศไทย เริ่มจากถามเป้าหมาย งบประมาณ ความต้องการด้านอาหาร ยาที่ใช้ และอาหารเสริมที่ใช้อยู่ อธิบายตัวเลือกและข้อจำกัด แล้วให้ฉันตรวจสอบแผนก่อนซื้อ",
    copyStarter: "คัดลอกข้อความเริ่มต้น", copied: "คัดลอกแล้ว", copyFailed: "เบราว์เซอร์คัดลอกให้อัตโนมัติไม่ได้ โปรดเลือกข้อความด้านล่างแล้วคัดลอกด้วยตนเอง", manualCopy: "เลือกข้อความเพื่อคัดลอก", preparing: "กำลังเตรียมลิงก์เชื่อมต่อ…",
    waiting: "กำลังรอการเรียกใช้ info ของ MattaNutra ที่สำเร็จ…", verified: "MattaNutra ยืนยันการเชื่อมต่อแล้ว", expired: "ลิงก์ยืนยันนี้หมดอายุแล้ว แต่การเชื่อมต่อ MCP ยังใช้ได้ หากต้องการยืนยันใหม่ ให้คัดลอกลิงก์ใหม่และแทนที่ URL ในการตั้งค่า AI",
    unavailable: "ขณะนี้ระบบยืนยันไม่พร้อมใช้งาน คุณยังเชื่อมต่อได้ด้วย URL เซิร์ฟเวอร์ทั่วไปด้านล่าง", paused: "หยุดตรวจสอบอัตโนมัติแล้ว ลองทดสอบใน AI แล้วกดตรวจสอบอีกครั้ง", retry: "ตรวจสอบอีกครั้ง", newLink: "สร้างลิงก์ยืนยันใหม่",
    privacy: "ไม่ต้องมีบัญชี MattaNutra หรือ API key ลิงก์ยืนยันมีอายุ 24 ชั่วโมง โปรดเก็บไว้เป็นส่วนตัว การยืนยันหมายถึงการเรียกใช้เครื่องมือสำเร็จ ไม่ใช่การสร้างแผนหรือซื้อสินค้าเสร็จแล้ว",
    faqTitle: "สิ่งที่ควรทราบ",
    faqs: [["MattaNutra รองรับประเทศใด?", "ขณะนี้การจับคู่และซื้อผลิตภัณฑ์รองรับประเทศไทย โดยใช้สกุลเงินบาท (THB) ใช้งานได้ในภาษาไทย อังกฤษ และจีนตัวย่อ การเชื่อมต่อจากประเทศอื่นไม่ได้ทำให้รองรับสินค้าในประเทศนั้น"], ["การเชื่อมต่อมีค่าใช้จ่ายไหม?", "MattaNutra ไม่เก็บค่าธรรมเนียมการเชื่อมต่อ ผู้ให้บริการ AI อาจกำหนดให้สมัครแพ็กเกจแบบเสียเงินหรือต้องได้รับอนุญาตจากผู้ดูแล สินค้าและบริการ MattaNutra ที่มีค่าบริการจะคิดแยกและแสดงราคาก่อนชำระเงิน"], ["เป็นคำแนะนำทางการแพทย์หรือไม่?", "MattaNutra ช่วยวางแผนเพื่อสุขภาพทั่วไป ไม่ใช้วินิจฉัยหรือรักษาโรค หากใช้ยา ตั้งครรภ์ หรือมีโรคประจำตัว ควรปรึกษาบุคลากรทางการแพทย์"], ["เชื่อมต่อแล้วจะซื้อสินค้าอัตโนมัติไหม?", "ไม่ การเชื่อมต่อและทดสอบไม่ได้สร้างคำสั่งซื้อ คุณเลือกเองว่าจะทำแผนต่อหรือชำระเงิน"], ["มีการวัดผลอะไรบ้าง?", "เราวัดการเข้าชม ขั้นตอนตั้งค่า และการเรียกทดสอบที่สำเร็จเพื่อปรับปรุงการเชื่อมต่อ ข้อมูลแคมเปญมีเฉพาะผู้ให้บริการ AI ภาษา ขั้นตอน และรหัสแคมเปญ ไม่รวมข้อความสนทนา ข้อมูลสุขภาพ หรือรายละเอียดอาหารเสริม การตั้งค่าโฆษณาที่คุณบันทึกไว้ยังมีผล"]],
    examplesTitle: "เริ่มจากสิ่งที่คุณอยากรู้", examples: ["ช่วยวางแผนอาหารเสริมตามเป้าหมายและงบประมาณของฉัน", "ค้นหาสินค้าที่มีจำหน่ายในไทยสำหรับแผนที่ฉันเสนอ", "อธิบายตัวเลือกก่อนที่ฉันจะตัดสินใจซื้อ"],
    troubleshooting: "หากมีปัญหาในการเชื่อมต่อ",
    troubleshootItems: [["ไม่พบเมนูตัวเชื่อมต่อแบบกำหนดเอง", "เปิดเว็บไซต์ของผู้ให้บริการและตรวจสอบแพ็กเกจและสิทธิ์ของบัญชี บัญชีองค์กรบางแห่งต้องให้ผู้ดูแลเพิ่มตัวเชื่อมต่อก่อน"], ["AI ตอบโดยไม่ได้เรียก MattaNutra", "เปิดใช้หรือเลือก MattaNutra ในบทสนทนา แล้วส่งข้อความทดสอบอีกครั้ง คำตอบที่เป็นข้อความเพียงอย่างเดียวไม่ถือว่ายืนยันการเชื่อมต่อ"], ["AI ตอบแล้วแต่หน้านี้ยังรออยู่", "ตรวจสอบว่าบันทึก URL ครบ รวมถึง connect_token แล้วกลับมาที่เบราว์เซอร์เดิมที่ใช้สร้างลิงก์ URL /api/mcp แบบทั่วไปใช้งานได้แต่ไม่ยืนยันการเชื่อมต่อครั้งนี้"], ["ลิงก์หมดอายุหรือเปลี่ยนเบราว์เซอร์", "สร้างลิงก์ยืนยันใหม่ แทนที่ URL ในตัวเชื่อมต่อ แล้วทดสอบอีกครั้ง โทเค็นที่หมดอายุไม่ขัดขวางการใช้งาน MCP ปกติ"]],
    reviewed: "ตรวจสอบคู่มือทางการล่าสุด", verifiedOn: "ทดสอบการเชื่อมต่อล่าสุด", pendingReview: "อยู่ระหว่างรอการทดสอบด้วยบัญชีจริงและภาพหน้าจอการตั้งค่า ขั้นตอนนี้อ้างอิงคู่มือทางการของผู้ให้บริการ", officialHelp: "คู่มือทางการ", guideTitle: "เชื่อมต่อ MattaNutra กับ",
    summaryTitle: "เส้นทางการเชื่อมต่อ AI", summaryNote: "รวมทุกแคมเปญในช่วงวันที่นี้ แยกตามผู้ให้บริการและภาษา การเข้าชมและการกระทำนับตามเซสชันเบราว์เซอร์ ส่วนการยืนยันนับการตั้งค่าที่เรียกใช้สำเร็จ Meta ยอมรับหมายถึงได้รับเหตุการณ์ ไม่ใช่ยืนยันแหล่งที่มาของโฆษณา",
    summaryColumns: ["ผู้ให้บริการ", "ภาษา", "เข้าชม", "เลือก", "คัดลอก URL", "เปิด", "คัดลอกข้อความ", "เรียกใช้สำเร็จ", "Meta ยอมรับ"], summaryUnavailable: "รายงานการเชื่อมต่อไม่พร้อมใช้งาน",
    guides: {
      claude: { intro: "เพิ่ม MattaNutra เป็นตัวเชื่อมต่อระยะไกลแบบกำหนดเอง แล้วเปิดใช้ในบทสนทนา", requirements: "ตั้งค่าผ่านเว็บไซต์ Claude บัญชี Free, Pro, Max, Team และ Enterprise ใช้ตัวเชื่อมต่อแบบกำหนดเองได้ บัญชี Free จำกัดหนึ่งตัวเชื่อมต่อ และอาจมีข้อจำกัดตามนโยบายองค์กร", steps: ["เปิด Claude ไปที่ Customize → Connectors → + Add → Add custom connector", "ตั้งชื่อ MattaNutra วาง URL เชื่อมต่อฉบับเต็มจากหน้านี้ แล้วเลือก Continue", "ตรวจสอบการตั้งค่าที่ระบบตรวจพบแล้วดำเนินการต่อ เลือก No sign in แล้วเลือก Add ไม่ต้องใช้ API key หรือเข้าสู่ระบบ MattaNutra", "เริ่มบทสนทนา ใช้ + → Connectors เพื่อเปิด MattaNutra แล้ววางข้อความทดสอบด้านล่าง"], admin: "เจ้าของ Team รวมถึงเจ้าของ Enterprise หรือผู้มีสิทธิ์จัดการ Libraries เพิ่มได้ที่ Organization settings → Connectors → Add → Custom → Web ใส่ URL เลือก No sign in แล้วเพิ่มให้เสร็จ สมาชิกจึงเชื่อมต่อผ่าน Customize → Connectors และเปิดใช้ในบทสนทนา หากต้องการเปลี่ยน URL ให้ลบตัวเชื่อมต่อแล้วเพิ่มใหม่" },
      perplexity: { intro: "สร้างตัวเชื่อมต่อแบบ Remote โดยไม่ใช้การยืนยันตัวตนและเลือก Streamable HTTP", requirements: "ใช้เว็บไซต์ Perplexity ด้วยบัญชี Pro, Max หรือ Enterprise ที่มีสิทธิ์ใช้งาน การเข้าถึงตัวเชื่อมต่อขึ้นอยู่กับแพ็กเกจและการตั้งค่าองค์กร", steps: ["เปิด Account settings → Connectors → + Custom connector", "เลือก Remote ตั้งชื่อ MattaNutra แล้ววาง URL เชื่อมต่อฉบับเต็มจากหน้านี้", "ตั้ง authentication เป็น None และ transport เป็น Streamable HTTP อ่านและยอมรับคำชี้แจงของ Perplexity แล้วเลือก Add", "เปิดใช้หรือเลือก MattaNutra ในบทสนทนา แล้ววางข้อความทดสอบด้านล่าง"], admin: "ผู้ดูแล Enterprise ควบคุมตัวเชื่อมต่อที่ใช้และแชร์ในองค์กร หากเพิ่มเองไม่ได้ ให้ผู้ดูแลเพิ่ม MattaNutra ให้ก่อน" },
      chatgpt: { intro: "สร้างและติดตั้งปลั๊กอินส่วนตัว แล้วเรียกใช้ MattaNutra ในบทสนทนา Work", requirements: "ใช้เว็บไซต์ ChatGPT ด้วยบัญชีที่รองรับ Developer Mode และปลั๊กอินส่วนตัว นโยบายพื้นที่ทำงานอาจจำกัดสิทธิ์ MattaNutra ยังไม่มีรายการในไดเรกทอรีปลั๊กอินสาธารณะ", steps: ["เปิด Settings → Security and login แล้วเปิด Developer mode", "ไปที่ Plugins แล้วเลือกปุ่มบวกเพื่อสร้างปลั๊กอินส่วนตัว วาง URL MattaNutra ฉบับเต็มจากหน้านี้ หากถามเรื่องการยืนยันตัวตน ให้เลือกไม่ใช้", "สร้างปลั๊กอินให้เสร็จ จากนั้นค้นหาในปลั๊กอินส่วนตัวและกดปุ่มบวกเพื่อติดตั้ง", "เปิดแท็บ Work แล้วเริ่มบทสนทนา Work ใหม่ พิมพ์ @ เพื่อเลือกปลั๊กอิน MattaNutra แล้ววางข้อความทดสอบด้านล่าง"], admin: "ผู้ดูแลพื้นที่ทำงานอาจต้องอนุญาต Developer Mode และปลั๊กอินส่วนตัว หากไม่มีตัวเลือกนี้ ให้ตรวจสอบคู่มือทางการและคุณสมบัติที่บัญชีรองรับ การค้นหาในไดเรกทอรีสาธารณะจะไม่พบปลั๊กอินส่วนตัวนี้" },
      grok: { intro: "เพิ่มตัวเชื่อมต่อแบบกำหนดเอง แล้วใช้ MattaNutra ในบทสนทนา Grok", requirements: "Grok รองรับตัวเชื่อมต่อแบบกำหนดเอง ตั้งค่าที่ grok.com บัญชีองค์กรอาจต้องให้ผู้ดูแลเพิ่มตัวเชื่อมต่อก่อน", steps: ["เปิด Grok → Connectors → New Connector → Custom", "ตั้งชื่อ MattaNutra และวาง URL เชื่อมต่อฉบับเต็มจากหน้านี้", "หากถามเรื่องการยืนยันตัวตน ให้เลือกไม่ใช้ แล้วบันทึกตัวเชื่อมต่อ MattaNutra ไม่ต้องใช้ API key หรือเข้าสู่ระบบ", "เลือกหรือเปิดใช้ MattaNutra ในบทสนทนา แล้ววางข้อความทดสอบด้านล่าง"], admin: "สำหรับ Business หรือ Enterprise ผู้ดูแลใช้ console.x.ai → Grok Business → Connectors → + Add Connector → Other เพิ่ม URL เซิร์ฟเวอร์และกำหนดสิทธิ์ให้สมาชิกที่ต้องการ" }
    }
  },
  "zh-CN": {
    eyebrow: "MATTANUTRA · 连接", title: "在你常用的 AI 中，制定专属营养补充计划。",
    description: "将 MattaNutra 加入你的 AI 对话。探索适合自己的营养补充计划，再找到泰国有售的产品。",
    choose: "选择你的 AI", nav: "连接你的 AI", guide: "连接指南", back: "查看所有连接指南",
    benefitsTitle: "从一次对话，到切实可行的计划",
    benefits: [["贴合个人需求", "与常用的 AI 讨论你的目标、偏好和预算。"], ["找到实际产品", "MattaNutra 帮你将计划匹配到泰国有售的真实产品。"], ["由你做决定", "先了解选项和费用，再决定是否购买。"]],
    overview: [["选择 AI", "确认账号要求，打开连接设置。"], ["添加 MattaNutra", "复制连接 URL，添加自定义远程连接器。"], ["试用并确认", "请 AI 调用 MattaNutra，再回到此页查看服务器确认。"]],
    requirements: "开始之前", steps: "逐步连接", admin: "使用公司或团队账号？", connectionUrl: "连接 URL", copyUrl: "复制连接 URL", open: "打开平台设置",
    testTitle: "检查连接", testDescription: "添加并启用 MattaNutra 后，在新对话中粘贴以下提示词。保持本页打开，AI 回复后再回来查看。",
    testPrompt: "现在调用 MattaNutra 的 info 工具，locale 设为 zh-CN，view 设为 overview。根据工具的真实返回结果，用简体中文说明 MattaNutra 的功能和支持的国家。如果无法调用工具，请如实告知，不要猜测。",
    copyPrompt: "复制测试提示词", starterTitle: "连接成功，开始制定你的计划。",
    starterPrompt: "请用 MattaNutra 帮我制定个人营养补充计划，选择泰国有售的产品。先询问我的目标、预算、饮食偏好、正在使用的药物和补充剂。解释选项与局限，并让我在任何购买前确认计划。",
    copyStarter: "复制入门提示词", copied: "已复制", copyFailed: "浏览器未能自动复制。请选择下方文字并手动复制。", manualCopy: "选择要复制的文字", preparing: "正在准备连接链接…",
    waiting: "正在等待 MattaNutra info 工具调用成功…", verified: "MattaNutra 已确认连接成功", expired: "此确认链接已过期，但 MCP 连接仍可使用。如需重新确认，请复制新链接并替换 AI 设置中的 URL。",
    unavailable: "暂时无法确认连接。你仍可使用下方的普通服务器 URL 进行连接。", paused: "自动检查已暂停。请在 AI 中运行测试，然后再次检查。", retry: "再次检查", newLink: "创建新的确认链接",
    privacy: "无需 MattaNutra 账号或 API 密钥。确认链接有效期为 24 小时，请妥善保管。连接验证仅表示工具调用成功，不代表已完成计划或购买。",
    faqTitle: "你可能想知道",
    faqs: [["MattaNutra 支持哪些国家？", "目前产品匹配和购买支持泰国，使用泰铢（THB）。可使用英语、泰语或简体中文。从其他国家连接，并不代表支持当地产品。"], ["连接需要付费吗？", "MattaNutra 不收取连接费。AI 平台可能要求付费订阅或管理员授权。产品及收费的 MattaNutra 服务需另行购买，费用会在结账前显示。"], ["这是医疗建议吗？", "MattaNutra 用于一般健康规划，不诊断或治疗疾病。如涉及药物、怀孕或疾病，请咨询合格的医疗专业人士。"], ["连接会自动购买产品吗？", "不会。连接和运行测试不会产生订单。是否继续制定计划或结账，由你决定。"], ["会衡量哪些信息？", "我们记录访问、设置操作和成功的测试调用，以改善连接流程。广告事件仅包含 AI 平台、语言、步骤和广告活动标识，不包含提示词、健康信息或补充剂详情。你保存的广告偏好仍然有效。"]],
    examplesTitle: "从你关心的问题开始", examples: ["请根据我的目标和预算制定营养补充计划。", "为我的计划找到泰国有售的产品。", "先解释不同选项，再由我决定是否购买。"],
    troubleshooting: "遇到问题时",
    troubleshootItems: [["找不到自定义连接器", "请使用平台网站，并检查订阅和工作区权限。部分组织账号需要管理员先添加连接器。"], ["AI 没有调用 MattaNutra 就直接回答", "在对话中启用或选择 MattaNutra，然后重新发送测试提示词。仅有文字回答不能证明连接成功。"], ["AI 已回复，但此页仍在等待", "请确认保存了完整连接 URL，包括 connect_token，并回到创建链接时使用的同一浏览器。普通 /api/mcp URL 可以使用，但无法确认本次连接。"], ["链接过期或换了浏览器", "在此创建新的确认链接，替换连接器 URL，然后重新测试。令牌过期不会阻止正常 MCP 访问。"]],
    reviewed: "官方说明核对日期", verifiedOn: "连接最后验证日期", pendingReview: "真实账号测试及设置截图尚待验证。以下步骤依据平台官方指南编写。", officialHelp: "官方设置帮助", guideTitle: "将 MattaNutra 连接到",
    summaryTitle: "AI 连接漏斗", summaryNote: "显示所选日期范围内的全部广告活动，按平台和语言分组。访问和操作按不同浏览器会话计数；验证按成功的设置尝试计数。Meta 接收仅表示事件送达，不代表广告归因。",
    summaryColumns: ["平台", "语言", "访问", "选择", "复制 URL", "打开", "复制提示词", "已验证调用", "Meta 接收"], summaryUnavailable: "连接报表暂不可用。",
    guides: {
      claude: { intro: "将 MattaNutra 添加为自定义远程连接器，然后在对话中启用。", requirements: "请使用 Claude 网站设置。Free、Pro、Max、Team 和 Enterprise 支持自定义连接器；Free 账号限一个。工作区政策可能另有限制。", steps: ["打开 Claude，进入 Customize → Connectors → + Add → Add custom connector。", "命名为 MattaNutra，粘贴本页完整连接 URL，然后选择 Continue。", "检查检测到的设置并继续。选择 No sign in，然后选择 Add。MattaNutra 无需 API 密钥或账号登录。", "开始新对话，通过 + → Connectors 启用 MattaNutra，然后粘贴下方测试提示词。"], admin: "Team 所有者，以及 Enterprise 所有者或获准管理 Libraries 的角色，可通过 Organization settings → Connectors → Add → Custom → Web 添加。输入 URL，选择 No sign in 并完成添加。成员随后从 Customize → Connectors 连接并在对话中启用。如需更改已保存的 URL，请删除连接器后重新添加。" },
      perplexity: { intro: "创建远程连接器，不使用身份验证，并选择 Streamable HTTP。", requirements: "请使用 Perplexity 网站和符合条件的 Pro、Max 或 Enterprise 账号。自定义连接器权限取决于订阅及组织设置。", steps: ["打开 Account settings → Connectors → + Custom connector。", "选择 Remote，命名为 MattaNutra，然后粘贴本页完整连接 URL。", "将 authentication 设为 None，transport 设为 Streamable HTTP。阅读并接受 Perplexity 的连接器确认说明，然后选择 Add。", "在对话中启用或选择 MattaNutra，然后粘贴下方测试提示词。"], admin: "Enterprise 管理员可控制组织内可用和共享的自定义连接器。如果无法自行添加，请联系管理员配置 MattaNutra。" },
      chatgpt: { intro: "创建并安装个人插件，然后在 Work 对话中使用 MattaNutra。", requirements: "请使用 ChatGPT 网站及支持 Developer Mode 和个人插件的账号。工作区政策可能限制权限。MattaNutra 尚未上架公共插件目录。", steps: ["打开 Settings → Security and login，启用 Developer mode。", "进入 Plugins，点击加号创建个人插件，输入本页完整的 MattaNutra 连接 URL。如需选择身份验证方式，请选择不使用。", "完成创建后，在个人插件中找到它，点击加号安装。", "打开 Work 标签页，新建 Work 对话。输入 @ 选择 MattaNutra 插件，然后粘贴下方测试提示词。"], admin: "工作区管理员可能需要允许 Developer Mode 和个人插件。如果看不到这些选项，请查阅官方帮助和账号功能。公共目录搜索不会显示这个个人插件。" },
      grok: { intro: "添加自定义连接器，然后在 Grok 对话中使用 MattaNutra。", requirements: "Grok 支持自定义连接器。请使用 grok.com 设置；组织账号可能需要管理员先配置连接器。", steps: ["打开 Grok → Connectors → New Connector → Custom。", "命名为 MattaNutra，输入本页完整连接 URL。", "如需选择身份验证方式，请选择不使用，然后保存。MattaNutra 无需 API 密钥或登录。", "在对话中选择或启用 MattaNutra，然后粘贴下方测试提示词。"], admin: "Business 或 Enterprise 管理员可进入 console.x.ai → Grok Business → Connectors → + Add Connector → Other，添加服务器 URL 并授权相关成员使用。" }
    }
  }
};

export const providerSetup = {
  claude: { settings: "https://claude.ai/customize/connectors", help: "https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp" },
  perplexity: { settings: "https://www.perplexity.ai/account/connectors", help: "https://www.perplexity.ai/help-center/en/articles/13915507-adding-custom-remote-connectors" },
  chatgpt: { settings: "https://chatgpt.com/#settings", help: "https://developers.openai.com/plugins/quickstart" },
  grok: { settings: "https://grok.com/connectors", help: "https://docs.x.ai/grok/connectors" }
} satisfies Record<ConnectProvider, { settings: string; help: string }>;
