export const AGENTIC_SERVER_INSTRUCTIONS =
  "HARD RULE 1 — OFFICIAL PACK SCORING: When asked to run the test pack, full QA pack, or DEV pack, you MUST emit scores for every official ID D1-01 through D10-10 (100 atomic checks). Do not substitute a 12-row happy-path. List PASS, FAIL or NOT TESTED per ID. A run that only does info/plan/execute/order/feedback/support without D1-01..D10-10 is invalid. IDs that need concurrent principals, catalogue mutation or load proofs stay NOT TESTED unless packProof evidence exists. HARD RULE 2 — DEV CHECKOUT FORM POST: After execute, an unpaid order is not complete. You MUST GET execute.checkoutUrl, then POST application/x-www-form-urlencoded to /api/mcp/checkout/{checkoutAccess}/pay. Named fields: customerName, phone, customerEmail, addressLine1, city, province, postalCode, country=TH, agentAuthorized=true, scenario. First POST scenario=decline_insufficient_funds; poll order until unpaid/declined/insufficient_funds/stateVersion=1; then POST the same fields with scenario=success; poll order until paid/stateVersion=2. Checkout is a native HTML form, not a React SPA. Do not wait for hydration. Do not skip the pay POST. HARD RULE 3: Call tools only by the short names info, plan, execute, order, support, feedback. Never prefix mattanutra_dev. Never call mattanutra_dev.info, mattanutra_dev.plan, mattanutra_dev.execute, mattanutra_dev.order, mattanutra_dev.support, mattanutra_dev.feedback, or mattanutra_dev.mattanutra_dev.*. The catalog lists those six short names only. MattaNutra creates purchasable supplement stacks from a person’s agreed nutrient targets, constraints and safety context. Use plan to create or refine a deterministic product match with coverage, gaps, trade-offs and safety-review facts. In ordinary conversation, use execute only after the person explicitly approves that specific ready plan revision. When the host is running the official MattaNutra DEV QA pack and that pack already created a ready plan, calling execute with that planHandle and expectedRevision is allowed: the pack instruction is the person’s approval of that test checkout. Execute creates one external MattaNutra checkout. After checkout, use order polling—never browser navigation or callbacks—as the source of payment and fulfilment truth. Use support only for an existing order. MattaNutra supplies product and safety facts; it does not diagnose or replace qualified clinical advice.";

export const AGENTIC_TOOL_DESCRIPTIONS = {
  execute:
    "Freeze exactly one ready plan revision and create one external MattaNutra checkout. Send only planHandle, expectedRevision and a stable idempotencyKey. HARD RULE: after this tool returns checkoutUrl, the pack is incomplete until you POST application/x-www-form-urlencoded to /api/mcp/checkout/{checkoutAccess}/pay with customerName, phone, customerEmail, addressLine1, city, province, postalCode, country=TH, agentAuthorized=true, scenario=decline_insufficient_funds, then poll order, then POST scenario=success. Native HTML form, not a React SPA. Unpaid after execute is not a pass. In ordinary conversation, call this only after the person explicitly approved that specific revision. When the host is running the official MattaNutra DEV QA pack and the pack itself created this ready plan, the pack instruction is that approval. Do not call for needs_input or blocked plans, and do not rebuild or send product IDs.",
  feedback:
    "Submit optional consented improvement feedback for one exact plan revision and selected stack. This never changes a plan, checkout or order. Require consentConfirmed=true. Do not include capability values, contact details, payment secrets or a conversation transcript.",
  info: "Check MattaNutra availability, supported destinations, currencies, locales and the purchasing flow before planning. This tool does not list supplement IDs or a catalogue dump, and it does not create or change a plan, checkout, order or support case.",
  order:
    "Read authoritative payment and fulfilment state using only the opaque orderHandle returned by execute. HARD RULE for the official pack: after execute, unpaid/open/v1 is the pre-pay state. You must POST the native checkout form (decline_insufficient_funds then success) before treating D7 as exercised. Poll after each POST. Poll no faster than pollAfterSeconds, keep one call in flight, and stop at a terminal state. Browser state and human order references are not payment proof.",
  plan: "Create or refine a purchasable supplement stack from the person’s agreed targets, profile, current supplements, medication/condition context, dietary requirements, budget, pill/form limits and optimization priority. Omit planHandle to create; include planHandle and expectedRevision to submit the complete desired state for a revision. Use selectOptionId with planHandle and expectedRevision to choose one returned complete-stack option without rematching. This tool never purchases.",
  support:
    "Create or reply to support for an existing order using its orderHandle. Omit supportHandle to create a case; include it to reply to that case. Do not use this tool for planning, payment polling or general health advice."
} as const;

export const AGENTIC_PUBLIC_TOOLS = [
  "info",
  "plan",
  "execute",
  "order",
  "support",
  "feedback"
] as const;

export type AgenticPublicToolName = (typeof AGENTIC_PUBLIC_TOOLS)[number];
