import { Type, type TSchema, type Static } from "@sinclair/typebox";
import { AGENTIC_PUBLIC_TOOLS } from "@/lib/agentic/contract/names";
import { AGENTIC_ERROR_CATEGORIES, AGENTIC_REASON_CODES } from "@/lib/agentic/contract/errors";
import { enumeration as e, object as o, optional as p, nullable as n, PLAN_REQUEST, AGENTIC_INPUT_SCHEMAS } from "@/lib/agentic/contract/schemas";
const s = Type.String(); const num = Type.Number(); const int = Type.Integer(); const bool = Type.Boolean();
const a = <T extends TSchema>(item: T) => Type.Array(item);
const ss = a(s); const pn = <T extends TSchema>(item: T) => p(n(item));
const money = Type.Integer({ description: "Amount in the stated currency's minor units; unavailable values are null or absent, never fabricated zero." });
const status = e(["processing", "ready", "needs_input", "blocked", "no_purchase"] as const);
export const OPERATIONAL_DECISION_SCHEMA = o({ status, nextAction: e(["review_options", "poll_plan", "answer_questions", "change_request", "confirm_with_user", "replenish_later", "no_purchase", "split_request"] as const), purchaseEligible: bool });
const contributor = o({ amount: num, productName: s, unit: s, productId: p(s), source: p(e(["current", "selected", "diet"] as const)) });
const nutrient = o({ amount: num, name: s, unit: s });
const selection = o({ code: s, message: s, messageKey: s, requestedSupplementIds: ss, requestedNames: p(ss) });
export const ADMINISTRATION_SCHEMA = o({ route: e(["oral", "topical", "other", "unknown"] as const), physicalUnit: e(["capsule", "tablet", "softgel", "gummy", "drop", "ml", "g", "scoop", "sachet", "other", "unknown"] as const), unitsPerServing: n(num), doseIncrement: n(num), packQuantity: n(num), provenance: o({ status: e(["verified", "unverified", "conflicting"] as const), sourceUrl: n(s), sourceText: n(s), verifiedAt: n(s) }) }, "Physical administration evidence: unitsPerServing and packQuantity use physicalUnit; doseIncrement is the smallest measurable quantity in that unit. Null means unknown, never an inferred capsule or pack size. Servings per day multiply these labelled serving quantities; instructions and health reference limits remain advice.");
export const BASKET_ITEM_SCHEMA = o({ currency: s, dailyPills: n(num), pillCountKnown: p(bool), administration: pn(ADMINISTRATION_SCHEMA), labelledFacts: p(a(o({ name: s, amount: n(num), unit: n(s), confidence: e(["high", "moderate", "low"] as const), mappingStatus: e(["verified", "unverified", "conflicting"] as const), sourceUrl: n(s), sourceText: n(s) }))), form: s, lineTotalMinor: money, pillsPerServing: n(num), productId: s, productName: s, quantity: num, servingsPerDay: num, unitPriceMinor: money, selectionReason: p(selection), daysOfSupply: pn(num), servingsPerPack: pn(num), availableServings: pn(num), leftoverServings30: pn(num), leftoverServings90: pn(num), replenishmentDay: pn(num), requestedNutrientNames: p(ss), requestedNutrients: p(a(nutrient)), incidentalNutrientNames: p(ss), incidentalNutrients: p(a(nutrient)), incidentalOmittedCount: p(int), imageUrl: p(s), fixture: p(bool), source: p(e(["fixture", "retail"] as const)) });
const coverage = o({ referenceConfidence: p(e(["high", "moderate", "low"] as const)), basisRationale: p(s), basis: p(e(["total_daily", "supplemental"] as const)), coveragePercent: num, currentAmount: num, deliveredAmount: num, name: s, remainingGap: num, excess: p(num), withinAgreedRange: p(bool), requestedAmount: num, status: e(["already_covered", "conditional_deferred", "covered", "gap", "optional_omitted", "over_target", "partial", "uncovered", "upper_limit_risk"] as const), supplementId: pn(s), totalExposureAmount: pn(num), quantifiedExposureAmount: p(num), totalExposureComplete: p(bool), intakeCertainty: p(e(["known", "estimated", "unknown"] as const)), requestedTargetId: p(s), unresolved: p(bool), unit: s, claimIds: p(ss), importance: p(e(["core", "optional", "conditional", "required"] as const)), reasonCode: p(s), nextAction: p(s), contributors: p(a(contributor)), upperLimitAmount: p(num), percentOfUpperLimit: p(num), sourceScope: p(e(["supplemental", "total"] as const)), authorityUrl: p(s), ruleId: p(s), rulesVersion: p(s), populationScope: p(s), safetyLedgerVersion: p(s), uncertainty: p(s) });
const adviceCore = { kind: p(e(["dose_review", "interaction", "overlap", "incomplete_information", "product_data", "other"] as const)), comparator: pn(e(["gt", "gte", "lt", "lte", "eq"] as const)), guidanceId: s, severity: e(["high", "info", "blocking"] as const), message: s, nutrientName: pn(s), exposure: pn(num), threshold: pn(num), unit: pn(s), contributors: p(a(contributor)), ruleId: s, rulesVersion: s, sourceScope: pn(e(["supplemental", "total"] as const)), authorityUrl: pn(s), evidence: p(ss), uncertainty: p(s) };
export const ADVICE_SCHEMA = o({ ...adviceCore, referenceConfidence: p(e(["high", "moderate", "low"] as const)), basisRationale: p(s), uncertaintyCodes: p(ss), referenceBasis: p(Type.Literal("continued_dose")), action: p(e(["review", "acknowledge", "block"] as const)), acknowledgementStatus: p(e(["not_required", "pending", "acknowledged", "not_applicable"] as const)), code: p(s), messageKey: p(s), productIds: p(ss), supplementIds: p(ss) });
const stackSummary = o({ currency: s, dailyCostMinor: n(money), productCount: int, supplyDays: n(num), totalDailyPills: n(num), totalPriceMinor: money });
const tradeoffs = o({ coverageDeltaPercent: num, pillDelta: n(num), priceDeltaMinor: money, productCountDelta: int, summary: s, summaryKey: s });
const retained = o({ avoidedPurchase: bool, daysRemaining: p(num), name: s, productId: p(s), supplementId: s });
const unavailable = o({ dimension: s, reasonCode: s, missingFieldNames: ss, dependentCapabilities: ss });
const baselineLine = o({ lineTotalMinor: money, productId: s, quantity: num, unitPriceMinor: money });
const comparisonBasis = o({ catalogueSnapshotId: p(s), catalogId: p(s), costHorizonsDays: p(a(num)), destinationCountry: p(s), orderBoundary: p(s), rounding: p(s), baselineType: p(s), comparator: p(s), coverageEquivalent: p(bool), horizonDays: p(num), currency: p(s), currentInventory: p(a(o({ daysRemaining: pn(num), productId: pn(s), supplementId: s }))), baselineItems: p(a(baselineLine)), baselineCoverage: p(a(coverage)), selectedCoverage: p(a(coverage)), shippingIncluded: p(bool) });
const economics = o({ baseline: p(o({ cash90DayMinor: pn(money), lines: p(a(baselineLine)), reasonCode: pn(s), type: p(s) })), cash30DayMinor: pn(money), cash90DayMinor: pn(money), cashTotalMinor: pn(money), comparisonBasis: p(comparisonBasis), complete: p(bool), cashComplete: p(bool), comparisonComplete: p(bool), consumptionComplete: p(bool), consumptionScope: p(e(["full_horizon", "newly_purchased"] as const)), consumption30DayMinor: pn(money), consumption90DayMinor: pn(money), unavailableReasons: p(a(unavailable)), deltas: p(o({ administrations: num, coverage: num, pills: n(num), products: num })), equivalent: p(bool), firstOrderSubtotalMinor: p(money), otherCustomerCostMinor: p(money), savingClaim: p(e(["loss", "none", "positive"] as const)), savings90DayMinor: pn(money), savings90DayPercent: pn(num), shippingMinor: p(money) });
export const DOSE_FIT_SCHEMA = o({ version: s, limitWeight: Type.Literal(2), under: num, over: num, limit: num, weightedLimit: num, total: num, perTarget: a(o({ subjectId: s, name: s, unit: s, basis: p(e(["total_daily", "supplemental"] as const)), target: num, exposure: num, under: num, over: num, exposureMinimum: p(num), exposureMaximum: p(num), conservativeExposure: p(num), acceptableMinimum: p(num), acceptableMaximum: p(num), withinAcceptableRange: p(bool), certainty: e(["known", "estimated", "unknown"] as const) })), perContinuedDose: p(a(o({ subjectId: s, name: s, unit: s, referenceDose: num, exposure: num, exposureMinimum: p(num), exposureMaximum: p(num), conservativeExposure: p(num), over: num, certainty: e(["known", "estimated", "unknown"] as const), referenceBasis: Type.Literal("continued_dose"), sourceIds: ss }))), perLimit: a(o({ subjectId: s, name: s, unit: s, exposure: num, limit: num, excess: num, exposureMinimum: p(num), exposureMaximum: p(num), conservativeExposure: p(num), sourceScope: e(["supplemental", "total"] as const), ruleId: pn(s), authorityUrl: pn(s), certainty: e(["known", "estimated", "unknown"] as const) })), unknownSubjectIds: ss, estimatedSubjectIds: ss }, "Dimensionless normalized dose deviation: 1 equals 100%. total=under+over+2*limit, using symmetric deviations from requested targets, normalized newly added dose above an explicitly known continued-dose reference for unrequested nutrients, and additional applicable upper-limit excess. Unknown or estimated continued doses never create a reference denominator. This is a dose-fit ranking measure, not a clinical risk or approval score.");
const exactPenalty = o({ numerator: Type.String({ pattern: "^[0-9]+$", description: "Nonnegative exact integer numerator." }), denominator: Type.String({ pattern: "^[1-9][0-9]*$", description: "Positive exact integer denominator." }) });
const importance = e(["flexible", "normal", "strong"] as const);
const preferencePenalty = o({ active: bool, actual: n(num), actualLowerBound: num, preferred: n(num), complete: bool, scale: n(num), importance, multiplier: num, penalty: num }, "Quadratic advisory overrun: 0.25 × profile multiplier × importance (0.25/1/4) × (positive overrun / scale)^2. Incomplete amounts use a verified lower bound for scoring only; actual remains null. No eligibility cutoff.");
export const OVERALL_SCORE_SCHEMA = o({
  profile: o({ id: e(["balanced", "best_coverage", "fewest_pills", "lowest_cost"] as const), version: s, hash: s,
    multipliers: o({ pills: num, products: num, price: num, servings: num }),
    importance: o({ maxDailyPills: importance, maxProductCount: importance, maxPriceMinor: importance }),
    pricePreferenceBasis: e(["first_order", "monthly_30_days"] as const) }),
  total: num, exact: exactPenalty, complete: bool,
  components: o({ pills: num, products: num, price: num, servings: num, uncertainty: num, preferences: num }),
  preferences: o({ maxDailyPills: preferencePenalty, maxProductCount: preferencePenalty, maxPriceMinor: preferencePenalty }),
  missingComponents: ss, dosePenalty: num, overallPenalty: num, overallExact: exactPenalty
}, "Versioned shared ranking breakdown. overallPenalty = unchanged raw dosePenalty + total practical penalty. Smaller is preferred under the same profile only, subject to required/core protection. Pills/products are daily; price is THB minor units. First-order price is used for routine cost, monthly_30_days only for an explicitly identified web budget preference. Uncertainty is disclosed, never a fabricated exact measurement. These optimisation scores are not medical risk ratings.");
const doseFit = DOSE_FIT_SCHEMA;
export const PREFERENCE_ASSESSMENT_SCHEMA = o({ kind: e(["product_count", "daily_pills", "first_order_goods_price", "monthly_goods_price"] as const), preferred: n(num), actual: n(num), actualLowerBound: p(Type.Number({ minimum: 0, description: "Verified nonnegative contributions when actual is unknown. This is a lower bound, not an exact total; exact delta and percentage stay null." })), unit: s, complete: bool, delta: n(num), percent: n(num), status: e(["not_requested", "within_preference", "above_preference", "unknown"] as const), prominent: bool, message: s, messageKey: s }, "Advisory numeric preference comparison. actual/preferred/delta use unit; percent is signed deviation from a positive preference and null for zero, absent preference or unknown actual. More than 20% above a positive preference, or any positive amount above zero, is prominent; selection and purchase remain available.");
export const MATCHING_DIAGNOSTICS_SCHEMA = o({ catalogueListings: int, catalogueProducts: int, eligibleListings: int, eligibleProducts: int, supportedDoseVariants: int, evaluatedNonemptyBaskets: int, reasonCode: e(["targets_already_covered", "empty_closest_fit", "catalogue_empty", "no_eligible_products", "no_supported_quantities", "no_evaluated_purchase", "search_incomplete", "purchase_options_available"] as const), rejectionCounts: a(o({ reason: s, count: int })), targets: a(o({ subjectId: s, name: s, candidateProducts: int, eligibleProducts: int, supportedDoseVariants: int })) }, "Snapshot candidate counts and work actually evaluated; not a proof that every global combination was searched. Listing and unique-product counts are separate. Numeric preferences and health advice never reject candidates.");
export const MATCHING_EXPLANATION_SCHEMA = o({ reasonCode: e(["targets_already_covered", "empty_closest_fit", "catalogue_empty", "no_eligible_products", "no_supported_quantities", "no_evaluated_purchase", "search_incomplete", "purchase_options_available", "explanation_unavailable"] as const), message: s, messageKey: s, recoveryActions: a(e(["review_options", "refine_request", "expand_search", "no_purchase"] as const)) });
export const OPTION_SCHEMA = o({ preferenceAssessment: p(a(PREFERENCE_ASSESSMENT_SCHEMA)), coveragePercent: Type.Number({ description: "Equal-weight average of capped proportional dose coverage across every requested target, including unresolved and optional targets. Partial coverage is distinct from fully met target count." }), coverageSummary: p(o({ coveragePercent: num, fullyMetCount: int, requestedCount: int })), optionId: s, reason: s, reasonCode: s, reasonKey: s, recommended: bool, selected: bool, stackSummary, tradeOffs: tradeoffs, roles: p(a(e(["best_match", "closest_dose", "lower_cost", "simpler", "fewer_concerns", "purchase_fallback"] as const))), purchaseEligible: p(bool), role: p({ ...e(["requested_objective", "lower_cost", "simpler", "purchase_fallback", "fewer_concerns", "best_value", "complete", "minimum_core"] as const), description: "requested_objective is the primary profile-weighted requested objective; fewer_concerns is a distinct unchanged-constraint alternative. Other values are legacy saved-plan roles." }), cash90DayMinor: p(money), tradeOff: p(o({ cash90DayDeltaMinor: n(money), coverageDelta: num, dailyPillsDelta: n(num) })), includedTargetIds: p(ss), omittedTargetIds: p(ss), deferredTargetIds: p(ss), retainedCurrent: p(a(retained)), economics: p(economics), basket: p(a(BASKET_ITEM_SCHEMA)), coverage: p(a(coverage)), advice: p(a(ADVICE_SCHEMA)), doseFit: p(doseFit), overallScore: p(OVERALL_SCORE_SCHEMA) });
const gap = o({ decisions: ss, deliveredAmount: num, name: s, reason: s, remainingGap: num, requestedAmount: num, supplementId: p(s), unit: s });
const question = o({ choices: a(o({ choice: s, label: s, labelKey: s })), prompt: s, promptKey: s, questionId: s, targets: p(a(gap)) });
const leftover = o({ name: s, reason: s, severity: p(s), amount: p(num), unit: p(s), supplementId: p(s), note: p(s), requestedAmount: p(num), deliveredAmount: p(num), remainingGap: p(num), source: p(e(["target", "current_supplement"] as const)), requestIndex: p(int) });
const scheduleOrder = o({ day: num, inventoryAfter: num, inventoryBefore: num, lines: a(baselineLine), nextReplenishmentDay: pn(num), otherCustomerCostMinor: money, productIds: ss, quantities: a(num), shippingMinor: money, shippingRuleId: s, shippingRuleVersion: s, subtotalMinor: money, totalMinor: money, type: e(["immediate", "replenishment"] as const) });
const schedule = Type.Union([a(scheduleOrder), o({ available: Type.Literal(false), reasonCode: s })]);
const canonical = o({ buildId: s, canonicalVersion: p(s), contractVersion: s, hash: s, matcherVersion: s, packVersion: s, catalogId: p(s), snapshotId: p(s) });
const compact = o({ highlightedAlternativeOptionId: pn(Type.String({ description: "Optional pointer to an existing selectable, nonempty, distinct positive-coverage option. Present the closest result and this alternative with their existing gaps, goods price and pill information. Null when none qualifies or continued intake already covers every target." })), preferenceAssessment: p(a(PREFERENCE_ASSESSMENT_SCHEMA)), matchingExplanation: p(MATCHING_EXPLANATION_SCHEMA), advice: a(ADVICE_SCHEMA), nextAction: s, operationalDecision: OPERATIONAL_DECISION_SCHEMA, cost: o({ cash30DayMinor: pn(money), cash90DayMinor: pn(money), currency: s, firstOrderMinor: pn(money) }), optionId: pn(s), status, what: ss, when: s, why: s });
const explanation = o({ administrations: num, cash30DayMinor: pn(money), cash90DayMinor: pn(money), conditionalDeferrals: a(o({ nextAction: pn(s), reasonCode: pn(s), status: s, supplementId: s })), firstOrderCashMinor: pn(money), nextAction: s, nextActionKey: s, optionalOmissions: a(o({ status: s, supplementId: s })), pills: n(num), productCount: int, purchases: a(o({ lineTotalMinor: money, productId: s, productName: s, quantity: num })), recommendedOptionId: s, retainedCurrent: a(retained), safetyState: s, savings90DayMinor: pn(money) });
export const PLAN_SUCCESS_SCHEMA = o({ preferenceAssessment: p(a(PREFERENCE_ASSESSMENT_SCHEMA)), matchingDiagnostics: p(MATCHING_DIAGNOSTICS_SCHEMA), matchingExplanation: p(MATCHING_EXPLANATION_SCHEMA), ok: Type.Literal(true), planHandle: s, revision: int, status, searchSummary: p(o({ effort: e(["standard", "expanded"] as const), expansionAttempts: int, expansionBudget: int, complete: bool, canExpand: bool })), doseFit: p(doseFit), alternativeSearch: p(o({ status: e(["found", "none_found", "incomplete", "not_needed"] as const), reason: s })), summary: s, summaryKey: s, locale: s, nextActions: ss, operationalDecision: p(OPERATIONAL_DECISION_SCHEMA), contractVersion: p(s), sourceContractVersion: p(s), refreshRequired: p(bool), originalRequest: p(PLAN_REQUEST), compactDecision: p(compact), claimIds: p(ss), researchVersion: p(s), evidenceHandle: p(s), basket: p(a(BASKET_ITEM_SCHEMA)), coverage: p(a(coverage)), comparisonBasis: p(comparisonBasis), nextReplenishmentDay: pn(num), orderSchedule: p(o({ "30": schedule, "90": schedule })), scheduleComplete: p(bool), purchaseRequiredNow: p(bool), reasonCode: p(s), cash30DayMinor: pn(money), cash90DayMinor: pn(money), cashComplete: p(bool), consumptionComplete: p(bool), comparisonComplete: p(bool), unavailableReasons: p(a(unavailable)), maxTargetsPerRequest: p(int), suggestedGroups: p(a(o({ names: ss, targets: a(nutrient) }))), unsupportedTargets: p(a(o({ amount: num, name: s, reason: s, unit: s }))), safetyScope: p(e(["complete", "partial"] as const)), assessedMedicationCodes: p(ss), unassessedMedicationCodes: p(ss), assessedConditionCodes: p(ss), unassessedConditionCodes: p(ss), medicationCodes: p(ss), conditionCodes: p(ss), acknowledgedUnassessedMedicationCodes: p(ss), acknowledgedUnassessedConditionCodes: p(ss), stackSummary: p(stackSummary), acknowledgementStatus: p(e(["not_required", "pending", "acknowledged"] as const)), shippingMinor: p(money), estimatedOrderTotalMinor: p(money), optionId: p(s), reason: p(s), reasonKey: p(s), tradeOffs: p(tradeoffs), questions: p(a(question)), gapReview: p(o({ targets: a(gap) })), leftovers: p(a(leftover)), safetyGuidance: p(a(ADVICE_SCHEMA)), guidanceIds: p(ss), options: p(a(OPTION_SCHEMA)), explanation: p(explanation), canonical: p(canonical), pollAfterSeconds: p(num), feedbackInvitation: p(o({ prompt: s, promptKey: s })) });
export const ERROR_SCHEMA = o({ ok: Type.Literal(false), error: o({ category: e(AGENTIC_ERROR_CATEGORIES), correlationId: p(s), currentRevision: p(int), errorCode: s, error_code: s, fieldPath: n(s), issues: p(a(o({ fieldPath: s, messageKey: s, reasonCode: s, message: p(s), permittedLimit: p(Type.Union([num, s, a(Type.Union([num, s, bool, Type.Null()]))])), actual: p(Type.Union([num, s])) }))), message: s, messageKey: s, nextAction: p(s), nextActions: p(ss), reasonCode: e(AGENTIC_REASON_CODES), requestedRevision: p(int), retryable: bool }) });
const country = o({ countryCode: s, countryName: s, currency: s });
const clientExample = Type.Union(AGENTIC_PUBLIC_TOOLS.map(tool => o({ name: s, tool: Type.Literal(tool), arguments: Type.Unsafe(AGENTIC_INPUT_SCHEMAS[tool]) })));
const INFO_SUCCESS = o({ clientInstructions: s, clientExamples: a(clientExample), clientGuideText: p(s), planSchemaJson: p({ ...s, description: "JSON-encoded schema generated from the selected plan operation contract. Parse this JSON for validation; no private API is required." }), planOperation: p(e(["create", "get", "revise", "answer", "select"] as const)), ok: Type.Literal(true), serviceName: s, contractVersion: s, schemaChecksum: s, buildId: s, supportedCountries: a(country), supportedLocales: ss, medicationCodes: ss, conditionCodes: ss, userAccountRequired: bool, continuation: Type.Literal("polling_only"), pollAfterSeconds: num, supportAvailable: bool, description: s, valuePropositionId: s, wellnessBoundary: s, researchVersion: s, responsibilityVersion: s, clientGuide: p(s), contractSchema: p(s) });
const responsibility = o({ version: s, domains: a(o({ domain: e(["guidance", "payment", "fulfilment", "support"] as const), semanticId: s, text: s })) });
const frozen = o({ contribution: p(o({ acquisitionMinor: money, attribution: s, currency: s, paymentFeeMinor: money, paymentMinor: money, productCostMinor: money, shippingSubsidyMinor: money })), catalogueVersion: p(s), channel: p(e(["agentic", "web"] as const)), countryCode: p(s), coveragePercent: p(num), currency: p(s), dailyPills: pn(num), items: a(BASKET_ITEM_SCHEMA), market: p(o({ retailerId: p(s), retailerName: p(s), countryCode: p(s), countryName: p(s), currency: p(s), country: p(s) })), planRevision: p(int), safetyGuidanceIds: p(ss), selectedOptionId: p(s), shippingMinor: p(money), subtotalMinor: p(money), taxMinor: p(money), totalPriceMinor: p(money), snapshotId: p(s) });
const orderStatus = e(["cancelled", "completed", "expired", "open"] as const);
const paymentStatus = e(["paid", "partially_refunded", "processing", "refunded", "unpaid"] as const);
const invitation = o({ prompt: s, promptKey: s });
const EXECUTE_SUCCESS = o({ ok: Type.Literal(true), checkoutExpiresAt: s, checkoutUrl: s, feedbackInvitation: invitation, frozenPlan: frozen, orderHandle: s, orderReference: s, orderStatus, paymentStatus, pollAfterSeconds: num, responsibility, responsibilityVersion: s, stateVersion: int, successUrl: p(s) });
const retail = o({ orderId: s, orderNumber: s, orderStatus: s, trackingUrl: s, contributionMargin: p(o({ currency: s, grossCustomerAmount: num, mattanutraMarginAmount: num, retailerPayableAmount: num, status: n(s) })) });
const ORDER_SUCCESS = o({ ok: Type.Literal(true), channel: e(["agentic", "web"] as const), checkoutExpiresAt: n(s), checkoutUrl: n(s), frozenOrder: frozen, fulfilment: o({ deliveryWindow: n(s), reasonCode: n(s), status: s, tracking: a(o({ number: s, url: s })) }), latestPaymentAttempt: n(s), latestPaymentReason: n(s), lookupStatus: Type.Literal("found"), message: s, messageKey: s, nextAction: e(["contact_support", "none", "open_checkout", "poll"] as const), orderReference: s, retailCustomerOrder: p(retail), orderStatus, paymentStatus, pollAfterSeconds: num, terminal: bool, receipt: n(o({ currency: s, paidAt: n(s), totalPriceMinor: money })), retryable: bool, stateVersion: int, acquisitionMinor: p(money), attribution: p(s), contributionMinor: pn(money), events: p(a(o({ createdAt: s, id: s, kind: e(["fulfilment", "order", "payment"] as const), sequence: p(int), status: s }))), money: p(o({ currency: s, items: a(o({ lineTotalMinor: money, productId: s, quantity: num })), totalPriceMinor: money })), paymentFeeMinor: p(money), paymentMinor: p(money), productCostMinor: p(money), responsibility: p(responsibility), shippingSubsidyMinor: p(money), timeline: p(s) });
const SUPPORT_SUCCESS = o({ ok: Type.Literal(true), caseReference: s, createdAt: s, feedbackInvitation: invitation, messageId: s, orderContext: n(o({ fulfilmentStatus: s, nextAction: s, orderStatus: s, paymentStatus: s, stateVersion: int, timeline: s })), responseExpectation: s, responseExpectationKey: s, retailCustomerOrder: p(retail), status: Type.Literal("open"), supportHandle: s, thread: a(o({ author: e(["client", "support"] as const), body: s, createdAt: s, id: s, sequence: int })) });
const EVIDENCE_SUCCESS = o({ ok: Type.Literal(true), claims: a(o({ claimId: s, limitation: s, researchVersion: s, reviewDate: s, source: s, statement: s, strength: s })), mode: e(["summary", "sources"] as const), planRevision: int, researchVersion: s });
// Presentation is a typed projection of the established full contracts. Canonical
// storage and legacy response fields remain untouched.
export const CONVERSATION_OPTION_KEYS = ["optionId", "roles", "reason", "stackSummary", "coveragePercent"] as const;
const conversationOption = o({ ...Type.Required(Type.Pick(OPTION_SCHEMA, CONVERSATION_OPTION_KEYS)).properties,
  reason: Type.String({ maxLength: 160 }) });
const detailSections = e(["request", "products", "coverage", "advice", "score", "economics"] as const);
const presentationBase = { ok: Type.Literal(true), planHandle: s, revision: int, resultVersion: s, contractVersion: s, locale: s, status };
export const PLAN_CONVERSATION_SCHEMA = o({ ...presentationBase, responseView: Type.Literal("conversation"),
  summary: s, operationalDecision: p(OPERATIONAL_DECISION_SCHEMA), nextActions: ss,
  selectedOptionId: n(s), highlightedAlternativeOptionId: n(s), options: a(conversationOption),
  advice: a(o({ adviceId: s, guidanceIds: ss, optionIds: ss,
    kind: e(["dose_review", "interaction", "overlap", "incomplete_information", "product_data", "other"] as const),
    severity: adviceCore.severity }, "References only. Fetch details.sections=[advice] for these optionIds to read complete findings and sources.")),
  planAdviceIds: Type.Array(s, { description: "Plan-wide flags in advice. Full plan-wide findings are available in details.sections=[advice].safetyGuidance." }),
  ...Type.Pick(PLAN_SUCCESS_SCHEMA, ["purchaseRequiredNow", "nextReplenishmentDay", "shippingMinor", "estimatedOrderTotalMinor", "questions", "pollAfterSeconds", "searchSummary", "refreshRequired", "sourceContractVersion", "reasonCode", "suggestedGroups", "unsupportedTargets", "evidenceHandle", "alternativeSearch"]).properties,
  availableDetails: a(detailSections) });
const detailOption = Type.Pick(OPTION_SCHEMA, ["optionId", "basket", "coverage", "advice", "doseFit", "overallScore", "economics"]);
export const PLAN_DETAILS_SCHEMA = o({ ...presentationBase, responseView: Type.Literal("details"), sections: a(detailSections),
  options: a(detailOption), ...Type.Pick(PLAN_SUCCESS_SCHEMA, ["originalRequest", "orderSchedule", "comparisonBasis", "unavailableReasons", "cash30DayMinor", "cash90DayMinor", "nextReplenishmentDay", "researchVersion", "claimIds", "safetyGuidance"]).properties });
export const PLAN_STATUS_SCHEMA = o({ ...presentationBase, responseView: Type.Literal("status"), unchanged: bool,
  pendingRevision: n(int), operationStatus: n(s), nextActions: ss, pollAfterSeconds: num, refreshRequired: bool,
  error: p(ERROR_SCHEMA.properties.error) });
export type PlanConversationWire = Static<typeof PLAN_CONVERSATION_SCHEMA>;
export type PlanDetailsWire = Static<typeof PLAN_DETAILS_SCHEMA>;
export type PlanStatusWire = Static<typeof PLAN_STATUS_SCHEMA>;
const orderReadBase = { ok: Type.Literal(true), orderHandle: s, resultVersion: s, contractVersion: s, locale: s };
export const ORDER_CONVERSATION_SCHEMA = o({ ...orderReadBase, responseView: Type.Literal("conversation"),
  ...Type.Pick(ORDER_SUCCESS, ["orderReference", "orderStatus", "paymentStatus", "fulfilment", "checkoutUrl", "checkoutExpiresAt", "message", "nextAction", "pollAfterSeconds", "terminal", "retryable", "stateVersion", "receipt", "latestPaymentReason"]).properties,
  currency: s, totalPriceMinor: money, subtotalMinor: n(money), shippingMinor: n(money), taxMinor: n(money), availableDetails: a(e(["frozen_order", "events"] as const)) });
export const ORDER_STATUS_SCHEMA = o({ ...orderReadBase, responseView: Type.Literal("status"), unchanged: bool,
  ...Type.Pick(ORDER_SUCCESS, ["orderReference", "orderStatus", "paymentStatus", "fulfilment", "nextAction", "pollAfterSeconds", "terminal", "retryable", "stateVersion", "latestPaymentReason"]).properties });
export const ORDER_DETAILS_SCHEMA = o({ ...orderReadBase, responseView: Type.Literal("details"), sections: a(e(["frozen_order", "events"] as const)),
  frozenOrder: p(frozen), events: ORDER_SUCCESS.properties.events });
export type OrderConversationWire = Static<typeof ORDER_CONVERSATION_SCHEMA>;
export type OrderStatusWire = Static<typeof ORDER_STATUS_SCHEMA>;
export type OrderDetailsWire = Static<typeof ORDER_DETAILS_SCHEMA>;
const result = <T extends TSchema>(success: T) => ({ type: "object", anyOf: [success, ERROR_SCHEMA] } as const);
export const AGENTIC_OUTPUT_SCHEMAS = { info: result(INFO_SUCCESS), plan: { type: "object", anyOf: [PLAN_SUCCESS_SCHEMA, PLAN_CONVERSATION_SCHEMA, PLAN_DETAILS_SCHEMA, PLAN_STATUS_SCHEMA, ERROR_SCHEMA] }, execute: result(EXECUTE_SUCCESS), order: { type: "object", anyOf: [ORDER_SUCCESS, ORDER_CONVERSATION_SCHEMA, ORDER_STATUS_SCHEMA, ORDER_DETAILS_SCHEMA, ERROR_SCHEMA] }, support: result(SUPPORT_SUCCESS), feedback: result(o({ ok: Type.Literal(true), accepted: Type.Literal(true) })), evidence: result(EVIDENCE_SUCCESS) } as const;

export type PlanSuccessWire = Static<typeof PLAN_SUCCESS_SCHEMA>;
export type PublicErrorWire = Static<typeof ERROR_SCHEMA>;
export type InfoSuccessWire = Static<typeof INFO_SUCCESS>;
export type ExecuteSuccessWire = Static<typeof EXECUTE_SUCCESS>;
export type OrderSuccessWire = Static<typeof ORDER_SUCCESS>;
export type SupportSuccessWire = Static<typeof SUPPORT_SUCCESS>;
export type EvidenceSuccessWire = Static<typeof EVIDENCE_SUCCESS>;
